name: Publish scrcpy static binaries
on:
  workflow_dispatch:
    inputs:
      scrcpy_version:
        description: "Version of scrcpy to use. Look up in its repo."
        default: "2.7"
        required: true
        type: string

jobs:
  darwin-arm64:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout scrcpy
        uses: actions/checkout@v4
        with:
          repository: Genymobile/scrcpy
          ref: v${{ inputs.scrcpy_version }}
          path: scrcpy-repo
      - name: Setup Build Environment
        run: |
          brew install meson ninja
      - name: Build static scrcpy
        run: |
          cp scripts/scrcpy-darwin-arm64.sh scrcpy-repo/scrcpy-darwin-arm64.sh
          cd scrcpy-repo
          ./scrcpy-darwin-arm64.sh ${{ inputs.scrcpy_version }} dist/scrcpy-v${{ inputs.scrcpy_version }}-darwin-arm64
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: scrcpy-darwin-arm64
          path: scrcpy-repo/dist

  linux-amd64:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout scrcpy
        uses: actions/checkout@v4
        with:
          repository: Genymobile/scrcpy
          ref: v${{ inputs.scrcpy_version }}
          path: scrcpy-repo
      - name: Build static scrcpy
        run: |
          cp scripts/scrcpy-linux-amd64.sh scrcpy-repo/scrcpy-linux-amd64.sh
          cd scrcpy-repo
          ./scrcpy-linux-amd64.sh ${{ inputs.scrcpy_version }} dist/scrcpy-v${{ inputs.scrcpy_version }}-linux-amd64
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: scrcpy-linux-amd64
          path: scrcpy-repo/dist

  open-pr:
    runs-on: ubuntu-latest
    needs: [darwin-arm64, linux-amd64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download scrcpy-server
        run: |
          mkdir -p bin
          curl -Lo bin/scrcpy-server-v${{ inputs.scrcpy_version }} "https://github.com/Genymobile/scrcpy/releases/download/v${{ inputs.scrcpy_version }}/scrcpy-server-v${{ inputs.scrcpy_version }}"
      - name: Download scrcpy for macOS
        uses: actions/download-artifact@v3
        with:
          name: scrcpy-darwin-arm64
          path: bin
      - name: Download scrcpy for Linux
        uses: actions/download-artifact@v3
        with:
          name: scrcpy-linux-amd64
          path: bin
      - name: Update checksums in formula
        run: |
          SHA_DARWIN_ARM64=$(shasum -a 256 bin/scrcpy-v${{ inputs.scrcpy_version }}-darwin-arm64 | cut -d ' ' -f 1)
          SHA_LINUX_AMD64=$(shasum -a 256 bin/scrcpy-v${{ inputs.scrcpy_version }}-linux-amd64 | cut -d ' ' -f 1)
          SHA_SERVER=$(shasum -a 256 bin/scrcpy-server-v${{ inputs.scrcpy_version }} | cut -d ' ' -f 1)
          sed -i '/# replace_with_darwin_arm64_sha256/ s/sha256 "[^"]*"/sha256 "'${SHA_DARWIN_ARM64}'"/' Formula/lim.rb
          sed -i '/# replace_with_linux_amd64_sha256/ s/sha256 "[^"]*"/sha256 "'${SHA_LINUX_AMD64}'"/' Formula/lim.rb
          sed -i '/# replace_with_server_sha256/ s/sha256 "[^"]*"/sha256 "'${SHA_SERVER}'"/' Formula/lim.rb
      - name: Open a pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.KARLIMBAR_BOT_TOKEN }}
          commit-message: |-
            Update scrcpy binaries to ${{ inputs.scrcpy_version }}
          title: Update scrcpy binaries to ${{ inputs.scrcpy_version }}
          body: |-
            Update scrcpy binaries to ${{ inputs.scrcpy_version }}
          branch: update-scrcpy-${{ inputs.scrcpy_version }}
          base: main
