name: Publish scrcpy static binaries
on:
  workflow_dispatch:
    inputs:
      scrcpy_version:
        description: "Version of scrcpy to use. Look up in its repo."
        default: "2.7"
        required: true
        type: string

jobs:
  darwin:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout scrcpy
        uses: actions/checkout@v4
        with:
          repository: Genymobile/scrcpy
          ref: v${{ inputs.scrcpy_version }}
          path: scrcpy-repo
      - name: Setup Build Environment
        run: |
          brew install meson ninja
      - name: Build static scrcpy
        run: |
          cp scripts/scrcpy-darwin-arm64.sh scrcpy-repo/scrcpy-darwin-arm64.sh
          cd scrcpy-repo
          ./scrcpy-darwin-arm64.sh ${{ inputs.scrcpy_version }} dist
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: scrcpy-darwin-arm64
          path: scrcpy-repo/dist

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout scrcpy
        uses: actions/checkout@v4
        with:
          repository: Genymobile/scrcpy
          ref: v${{ inputs.scrcpy_version }}
          path: scrcpy-repo
      - name: Setup Build Environment
        run: |
          apt-get install -y curl build-essential pkg-config meson ninja-build \
          libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev \
          libwayland-dev libxkbcommon-dev
      - name: Build static scrcpy
        run: |
          cp scripts/scrcpy-linux-amd64.sh scrcpy-repo/scrcpy-linux-amd64.sh
          cd scrcpy-repo
          ./scrcpy-linux-amd64.sh ${{ inputs.scrcpy_version }} dist
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: scrcpy-linux-amd64
          path: scrcpy-repo/dist
  open-pr:
    runs-on: ubuntu-latest
    needs: darwin
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download scrcpy for macOS
        uses: actions/download-artifact@v3
        with:
          name: scrcpy-darwin-arm64
          path: bin
      - name: Download scrcpy for Linux
        uses: actions/download-artifact@v3
        with:
          name: scrcpy-linux-amd64
          path: bin
      - name: Open a pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.KARLIMBAR_BOT_TOKEN }}
          commit-message: |-
            Update scrcpy binaries to ${{ inputs.scrcpy_version }}
          title: Update scrcpy binaries to ${{ inputs.scrcpy_version }}
          body: |-
            Update scrcpy binaries to ${{ inputs.scrcpy_version }}
          branch: update-scrcpy-${{ inputs.scrcpy_version }}
          base: main
